//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteGenerator.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Insuree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insuree()
        {
            this.AutoQuotes = new HashSet<AutoQuote>();
        }

        public int InsureeId { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [EmailAddress]
        public string EmailAddress { get; set; }
        [Required]
        public System.DateTime DateOfBirth { get; set; }
        [Range(1950, 2021)]
        public int VehicleYear { get; set; }
        [Required]
        public string VehicleMake { get; set; }
        [Required]
        public string VehicleModel { get; set; }
        public bool DUI { get; set; }
        [Required]
        public int SpeedingTickets { get; set; }
        public bool CoverageType { get; set; }
        public AutoQuote AutoQuote { get; set; }
        public AutoQuote AutoQuoteId { get; set; }
        public Nullable<decimal> MonthlyQuoteRate { get; set; }
        public Nullable<decimal> YearlyQuoteRate { get; set; }
        public ICollection<Insuree> Insurees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoQuote> AutoQuotes { get; set; }

        public Insuree(int InsureeId)
        {
        }

        public Insuree(int insureeId, string firstName, string lastName,
                      string emailAddress, DateTime dateOfBirth, int vehicleYear,
                      string vehicleMake, string vehicleModel, bool dui,
                      int speedingTickets, bool coverageType)

        {
        }

        public Insuree(AutoQuote autoQuoteId, AutoQuote monthlyQuoteRate, AutoQuote yearlyQuoteRate)
        {
        }

        public Insuree(AutoQuote AutoQuote)
        {
        }
    }
}
